#!/usr/bin/env python3

import saxo
import goodreads

@saxo.pipe
def current(arg):
    if len(arg) > 0:
        return goodreads.userCurrent(arg)
    else:
        return goodreads.groupBook(0); # 0 indicates we're looking for the current book