#!/usr/bin/env python3
 
import json
import saxo
 
@saxo.pipe
def ols(arg):
        if not arg:
                return "needs parameter!"
        url = "http://openlibrary.org/search.json"
        page = saxo.request(url, query={"title": arg})
        data = json.loads(page["text"])
        defs = data["docs"]
        if not defs:
                return "Sorry, no match found."
        title = defs[0]["title_suggest"]
        found_olid = defs[0]["edition_key"][0]
 
        url = "https://openlibrary.org/api/books"
        page = saxo.request(url, query={"bibkeys": 'OLID:%s' % found_olid, 'jscmd':'data', 'format': 'json'})
        data = json.loads(page["text"])
        ref = 'OLID:%s' % found_olid
        defs = data[ref]
        author = defs["authors"][0]["name"]
 
        return author
