#!/usr/bin/env python3

import os
import json
import saxo

@saxo.pipe
def ols(arg):
        if not arg:
                return "please specify a book title."
        url = "http://openlibrary.org/search.json"
        page = saxo.request(url, query={"title": arg})
        data = json.loads(page["text"])
        hits = data["numFound"]
        defs = data["docs"]
        if not defs:
                return "Sorry, no match found."
        title = defs[0]["title_suggest"]
        author = defs[0]["author_name"]
        olid = defs[0]["edition_key"]
        saxo.client("send", "PRIVMSG", os.environ.get("SAXO_SENDER"), "\002Matches found:\002 %i - \002Best hit:\002 %s %s - \002OLID:\002 %s" % (hits,title,author,olid[0]))
        #saxo.client("send", "PRIVMSG", os.environ.get("SAXO_SENDER"), "OLID Guess: %s" % olid[0])
        return

